# Generated by Django 2.2 on 2019-04-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='style',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
