# Generated by Django 2.2 on 2019-04-29 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20190429_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('picture', models.ImageField(upload_to='feed_pic')),
                ('create_date', models.DateTimeField()),
                ('expired_date', models.DateTimeField()),
                ('BarberShop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.BarberShop')),
            ],
        ),
    ]
