# Generated by Django 2.2 on 2019-05-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190503_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[('01', 1), ('02', 2), ('03', 3), ('04', 4), ('05', 5)], default='01', max_length=2),
        ),
    ]
