# Generated by Django 2.2 on 2019-05-02 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('01', 'waiting'), ('02', 'processing'), ('03', 'finish'), ('04', 'failure')], default='01', max_length=2)),
                ('start_queue', models.DateTimeField()),
                ('end_queue', models.DateTimeField()),
                ('ref_pic', models.ImageField(default='ref_queue_pic/default.jpg', upload_to='ref_queue_pic')),
                ('hairstyle', models.CharField(max_length=100, null=True)),
                ('barbershop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.BarberShop')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Customer')),
            ],
        ),
    ]
