# Generated by Django 2.2 on 2019-04-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='hairstyle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='queue',
            name='ref_pic',
            field=models.ImageField(null=True, upload_to='ref_queue_pic'),
        ),
    ]
