# Generated by Django 2.2 on 2019-05-03 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_queue', models.DateTimeField()),
                ('end_queue', models.DateTimeField()),
                ('status', models.CharField(choices=[('03', 'finish'), ('04', 'failure')], default='03', max_length=2)),
                ('barbershop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.BarberShop')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Customer')),
            ],
        ),
    ]
