# Generated by Django 2.2 on 2019-05-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='status',
            field=models.CharField(choices=[('03', 'finish'), ('04', 'failure'), ('05', 'success')], default='03', max_length=2),
        ),
    ]
